_DATA_FOLDER = "data/"
_JSON_FILE_EXTENSION = ".json"

COLOR_THEMES_PATH = _DATA_FOLDER + "color_themes" + _JSON_FILE_EXTENSION

USER_SETTINGS_PATH = _DATA_FOLDER + "user_settings" + _JSON_FILE_EXTENSION
